---
title: "codes_from_csv"
author: "Francisco Sanchez"
date: '2022-08-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("..", "Scripts", "Librerias.r"))
source(file.path("..", "Scripts", "Funciones.r"))

```

```{r}
# cargar datos-----------------------------------------------------------------
datos <- fread(file.path("Data", "preg_codes",
              "20221017_V2_ALL_full_codelist_pregnancy.csv"))

datos %>% count(coding_system)

```

```{r}
# limpiar base-----------------------------------------------------------------
datos_clean <- datos %>% filter(coding_system %in% c("ICD9CM", "ICD10", 
                                                     "ICD10CM", "ICD10DA"))

```

```{r}
datos_clean %>% distinct(event_definition)
datos_clean %>% distinct(event_definition, event_abbreviation)

```


```{r}
# interrupci칩n voluntaria del embarazo-----------------------------------------
datos_termination <- datos_clean %>% filter(event_definition %in% 
                c("Elective Termination Pregnancy"))

```

```{r}
# abortos espont치neos----------------------------------------------------------
datos_abortos_espont <- datos_clean %>% filter(event_definition %in% 
                c("Spontaneous abortion"))

```

```{r}
# muerte fetal-----------------------------------------------------------------
datos_stillbirth <- datos_clean %>% filter(event_definition %in% 
                c("Stillbirth"))

```

```{r}
# embarazo ect칩pico-----------------------------------------------------------
datos_ectopic <- datos_clean %>% filter(event_definition %in% 
                c("Ectopic pregnancy"))

```

```{r}
# ongoing y unknown------------------------------------------------------------
datos_ongoing <- datos_clean %>% filter(event_definition %in% 
                c("Ongoing Pregnancy"))

datos_livebirth <- datos_clean %>% filter(event_definition %in% 
                c("Livebirth"))

```

```{r}
# guardar datos----------------------------------------------------------------
lista_datos <- lst(datos_termination, 
                   datos_abortos_espont,
                   datos_stillbirth,
                   datos_ectopic,
                   datos_ongoing,
                   datos_livebirth)

write_xlsx(x = lista_datos, file.path("Data", "preg_codes",
                          "lista_codigos_embarazo_2022_10_24.xlsx"))

```

```{r}
lista_codigos <- lista_datos %>% purrr::map(.f = ~pull(.x, code))
lista_codigos_all <- list(all = datos_clean %>% pull(code) %>% str_c("^", .))

lista_codigos_and_procedures_all <- list(all = datos_clean %>% pull(code) |> 
append(c("72.0", "72.1", "72.2", "72.21", "72.29", "72.3", "72.31", "72.39", "72.4", "72.51", "72.53", "72.6", "72.7", "72.71", "72.79", "72.8", "72.9", "73.01", "73.1", "73.3", "73.4", "73.5", "73.59", "73.8", "73.9", "73.93", "73.94", "73.99", "74.0", "74.1", "74.2", "74.4", "74.9", "74.99", "75.7", "89.16", "72.5", "72.52", "72.54", "73.0", "73.09", "73.2", "73.22", "73.51", "73.91", "73.92", "74.3", "84.92", "84.93")) |> 
append(c("69.51", "74.91", "75.0", "69.01")) |> 
append(c("10A00ZZ", "10A03ZZ", "10A04ZZ", "10A07Z6", "10A07ZW", "10A07ZX", "10A07ZZ", "10A08ZZ")) |> 
append(c("69.52") ) |> 
append(c("66.62")) |> 
append(c("75.3", "75.32", "75.33", "75.34", "75.35", "75.36", "75.38", "75.2")) |> 
append(c("10900Z9", "10900ZA", "10900ZB", "10903Z9", "10903ZA", "10903ZB", "10904Z9", "10904ZA", "10904ZB", "10907Z9", "10907ZA", "10907ZB", "10908Z9", "10908ZA", "10908ZB", "BY30Y0Z", "BY30YZZ", "BY30ZZZ", "BY31Y0Z", "BY31YZZ", "BY31ZZZ", "BY32Y0Z", "BY32YZZ", "BY32ZZZ", "BY33Y0Z", "BY33YZZ", "BY33ZZZ", "BY35Y0Z", "BY35YZZ", "BY35ZZZ", "BY47ZZZ")) |> 
# encontrados mirando cmbd navarra
  append(c("O01", "O02", "O09", "O36", "O47", "O86", "O87", "O90", "O91", "O92", "O99", "Z39")) %>% 
  str_c("^", .))

saveRDS(lista_codigos, file.path("Data", "preg_codes", "lista_codigos.RDS"))
saveRDS(lista_codigos_all, file.path("Data", "preg_codes", "lista_codigos_all.RDS"))
saveRDS(lista_codigos_and_procedures_all, file.path("Data", "preg_codes", "lista_codigos_and_procedures_all.RDS"))

lista_codigos_and_procedures_all %>% enframe() %>% unnest() %>% filter(value == "^Z3A.4")
# Pensar bien y revisar como se ha buscado con los c칩digos del CMBD

```

