---
title: "Obtención microdato INE"
output: html_document
date: "2022-09-12"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r biblio,  eval=FALSE}
# referencias para extraer datos del INE---------------------------------------
https://ropenspain.es/paquetes/
https://github.com/orgs/rOpenSpain/repositories
https://rpubs.com/jaortega/EncuestaR1  #algunas rutinas, incluida la lectura de metadatos
https://www.icane.es/c/document_library/get_file?uuid=c2e9fff1-72d5-42ad-b391-bacb3ebe9dbe&groupId=10138  # curso de regresion en R que parte de microdatos del ine
https://rpubs.com/blad0914/746366 # introduccion a estadistica descriptiva
https://www.rpubs.com/lihkir/838523 # visualizacion de datos
https://www.cienciadedatos.net/documentos/31_seleccion_de_predictores_subset_selection_ridge_lasso_dimension_reduction  # Selección de predictores, regularización ridge, lasso, elastic net y reducción de dimensionalidad
https://elartedeldato.com/blog/como-visualizar-los-datos-de-la-epa-con-r/
http://destio.us.es/calvo/descargas/asig/demografia/RparaDemografia.pdf # r para demografia

```

```{r libraries}
# load libraries---------------------------------------------------------------
library(MicroDatosEs)   # defunciones, encuesta de presupuestos familiares, 
library(pxR)   # son para  json pc-axis
library(INEbaseR) 
library(purrr) # walk
library(tidyverse)
library(XLConnect)
library(stringr)
library(glue)
library(tictoc)
library(data.table)

```

# Descargar datos

***

```{r down,  eval=FALSE}
# data-------------------------------------------------------------------------

# A space in a file name (or direction) is a space in your soul
# spaces to %20

fetal_deaths_files <- c(
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet20.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet19.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet18.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet17.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet16.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet15.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet14.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet13.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet12.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet11.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos_muefet10.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos%20muefet09.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos%20muefet08.zip",
        "https://www.ine.es/ftp/microdatos/mnp_muefet/datos%20muefet07.zip" )


birth_files <- c(
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos20.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos19.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos18.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos17.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos16.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos15.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos14.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos13.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos12.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos_nacimientos11.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos%20nacimientos10.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos%20nacimientos09.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos%20nacimientos08.zip",
        "https://www.ine.es/ftp/microdatos/mnp_nacim/datos%20nacimientos07.zip")


labor_files <- c(
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos20.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos19.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos18.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos17.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos16.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos15.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos14.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos13.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos12.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos11.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos10.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos09.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos08.zip",
        "https://www.ine.es/ftp/microdatos/mnp_partos/datos_partos07.zip" )


# metadata--------------------------------------------------------------------
metadata_files <- c(
         "https://www.ine.es/ftp/microdatos/mnp_partos/disreg_Partos.zip",
         "https://www.ine.es/ftp/microdatos/mnp_nacim/disreg_nacimientos.zip",
         "https://www.ine.es/ftp/microdatos/mnp_muefet/disreg_muefet.zip")

```

# Descomprimir datos

***

```{r down,  eval=FALSE}
# download data----------------------------------------------------------------
dir.create(file.path("data", "fetal_death"))
dir.create(file.path("data", "birth"))
dir.create(file.path("data", "labor"))
dir.create(file.path("data", "metadata"))

# download fetal death
walk(fetal_deaths_files,
     ~download.file(.x,
      destfile = file.path("data", "fetal_death", basename(.x)), mode = "wb"))

# download birth
walk(birth_files,
     ~download.file(.x,
      destfile = file.path("data", "birth", basename(.x)), mode = "wb"))

# download labor
walk(labor_files,
     ~download.file(.x,
      destfile = file.path("data", "labor", basename(.x)), mode = "wb"))

# download metadata
walk(metadata_files,
     ~download.file(.x,
      destfile = file.path("data", "metadata", basename(.x)), mode = "wb"))

```


```{r down,  eval=FALSE}
# unzip several files function-------------------------------------------------
unzip2 <- function(path){
dir(path, pattern = "zip") %>%
  paste0(path, "/", .) %>% 
  walk(unzip, exdir = path)
}

# unzip files------------------------------------------------------------------
unzip2(file.path("data", "fetal_death"))
unzip2(file.path("data", "birth"))
unzip2(file.path("data", "labor"))

# metadata
# problems with special characters (is done manual)
# unzip2(file.path("data", "metadata"))

```

# Cambiar nombres

***

Se homogenizan los nombres de los ficheros a mano.

<br>

# Obtener tablas con los microdatos

***

## function fcar

```{r funciones read.fwf.microdata, eval=FALSE}
# función para leer los microdatos
fcar <- function(fichero_micro, fichero_meta, save_name) {

# Inicio temporizador
tic()

####################     INICIO     #########################
cat("\n Inicio: ")

#Lectura del fichero de metadatos (METAD), Hoja "Diseño" de archivo .xlsx
# Leer excel a partir de la fila 4
df <- readxl::read_excel(fichero_meta, skip = 3)

# Lectura del fichero de microdatos (MICROD)
df1 <- read.fwf(file = fichero_micro, 
                            # colClasses = tipDatos
                            widths = df$Longitud
                            )
  
# Aplicamos los nombres de la cabecera del registro
names(df1) <- df$Nombre

fwrite(df1, file.path("data", "procesados", save_name))

# Mensaje final ##########################################
cat("\n Fin del proceso de lectura: ")

# Fin temporizador
toc()

}

```

## Obtener datos nacimientos procesados

***

```{r, eval=FALSE}
# Obtener nacimientos procesados-----------------------------------------------
path_birth <- file.path("data", "birth")

# prueba
# fcar(fichero_micro = file.path(path_birth, "Microdatos_Nacimientos_A2007.txt"),
#      fichero_meta = file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
#      save_name = "birth_2007.csv")

# list of arguments for the function
lista_micro <- c(
  file.path(path_birth, "Microdatos_Nacimientos_A2007.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2008.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2009.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2010.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2011.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2012.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2013.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2014.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2015.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2016.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2017.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2018.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2019.txt"),
  file.path(path_birth, "Microdatos_Nacimientos_A2020.txt")
  )

lista_meta <- c(
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos_07_15.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_birth, "meta", "Diseñoanonimizadonacimientos2016 y sigs_con nestudios-ocupac_rela.xls")
  )

lista_save <- c(
  "birth_2007.csv",
  "birth_2008.csv",
  "birth_2009.csv",
  "birth_2010.csv",
  "birth_2011.csv",
  "birth_2012.csv",
  "birth_2013.csv",
  "birth_2014.csv",
  "birth_2015.csv",
  "birth_2016.csv",
  "birth_2017.csv",
  "birth_2018.csv",
  "birth_2019.csv",
  "birth_2020.csv"
  )

pwalk(
  # define the arguments of the function
  .l = list(fichero_micro = lista_micro, 
                fichero_meta = lista_meta, 
                save_name = lista_save), 
  # call the function
  .f = fcar)

```


## Obtener datos muerte fetal procesados

***

```{r}
# obtener fetal death----------------------------------------------------------
# prueba
path_fetal_death <- file.path("data", "fetal_death")
# fcar(fichero_micro = file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2007.txt"),
#      fichero_meta = file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
#      save_name = "fetal_death_2007.csv")

# list of arguments for the function
lista_micro <- c(
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2007.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2008.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2009.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2010.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2011.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2012.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2013.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2014.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2015.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2016.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2017.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2018.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2019.txt"),
  file.path(path_fetal_death, "Microdatos_Muerte_Fetal_A2020.txt")
  )

lista_meta <- c(
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT_07_15.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT2016 y sigs_con nestudios-ocupac_rela.xls"),
  file.path(path_fetal_death, "meta", "DiseñoanonimizadoMFT2016 y sigs_con nestudios-ocupac_rela.xls")
  )

lista_save <- c(
  "fetal_death_2007.csv",
  "fetal_death_2008.csv",
  "fetal_death_2009.csv",
  "fetal_death_2010.csv",
  "fetal_death_2011.csv",
  "fetal_death_2012.csv",
  "fetal_death_2013.csv",
  "fetal_death_2014.csv",
  "fetal_death_2015.csv",
  "fetal_death_2016.csv",
  "fetal_death_2017.csv",
  "fetal_death_2018.csv",
  "fetal_death_2019.csv",
  "fetal_death_2020.csv"
  )

pwalk(
  # define the arguments of the function
  .l = list(fichero_micro = lista_micro, 
                fichero_meta = lista_meta, 
                save_name = lista_save), 
  # call the function
  .f = fcar)


```

## Obtener datos partos procesados

***

```{r, eval=FALSE}
# Obtener nacimientos procesados-----------------------------------------------
path_labor <- file.path("data", "labor")

# prueba
# fcar(fichero_micro = file.path(path_labor, "Microdatos_Partos_A2007.txt"),
#      fichero_meta = file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
#      save_name = "labor_2007.csv")

# list of arguments for the function
lista_micro <- c(
  file.path(path_labor, "Microdatos_Partos_A2007.txt"),
  file.path(path_labor, "Microdatos_Partos_A2008.txt"),
  file.path(path_labor, "Microdatos_Partos_A2009.txt"),
  file.path(path_labor, "Microdatos_Partos_A2010.txt"),
  file.path(path_labor, "Microdatos_Partos_A2011.txt"),
  file.path(path_labor, "Microdatos_Partos_A2012.txt"),
  file.path(path_labor, "Microdatos_Partos_A2013.txt"),
  file.path(path_labor, "Microdatos_Partos_A2014.txt"),
  file.path(path_labor, "Microdatos_Partos_A2015.txt"),
  file.path(path_labor, "Microdatos_Partos_A2016.txt"),
  file.path(path_labor, "Microdatos_Partos_A2017.txt"),
  file.path(path_labor, "Microdatos_Partos_A2018.txt"),
  file.path(path_labor, "Microdatos_Partos_A2019.txt"),
  file.path(path_labor, "Microdatos_Partos_A2020.txt")
  )

lista_meta <- c(
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_07_15.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_16_20.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_16_20.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_16_20.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_16_20.xls"),
  file.path(path_labor, "meta", "Diseñoanonimizadopartos_16_20.xls")
  )

lista_save <- c(
  "labor_2007.csv",
  "labor_2008.csv",
  "labor_2009.csv",
  "labor_2010.csv",
  "labor_2011.csv",
  "labor_2012.csv",
  "labor_2013.csv",
  "labor_2014.csv",
  "labor_2015.csv",
  "labor_2016.csv",
  "labor_2017.csv",
  "labor_2018.csv",
  "labor_2019.csv",
  "labor_2020.csv"
  )

pwalk(
  # define the arguments of the function
  .l = list(fichero_micro = lista_micro, 
                fichero_meta = lista_meta, 
                save_name = lista_save), 
  # call the function
  .f = fcar)

```



